packages:
  # all packages in direct subdirs of packages/
  - "packages/*"
  # all packages in subdirs of components/
  - "components/**"
  # exclude packages that are inside test directories
  - "!**/test/**"
  # include tooling packages
  - "tooling/*"

allowBuilds:
  electron-winstaller: true
  esbuild: true
  sharp: true

catalogs:
  build:
    vite: ^8.1.3
    tsdown: ^0.22.3

  react:
    '@vitejs/plugin-react': ^6.0.3
    react: ^19.2.0
    react-dom: ^19.2.0

  tanstack:
    '@tanstack/devtools-vite': ^0.6.0
    '@tanstack/react-devtools': ^0.10.2
    '@tanstack/react-query': ^5.100.10
    '@tanstack/react-router': ^1.169.1
    '@tanstack/react-router-devtools': ^1.166.13
    '@tanstack/react-router-ssr-query': ^1.166.12
    '@tanstack/react-start': ^1.167.62
    '@tanstack/router-plugin': ^1.167.32

  test:
    '@testing-library/jest-dom': ^6.9.1
    '@testing-library/react': ^16.3.2
    '@testing-library/user-event': ^14.6.1
    '@vitest/coverage-v8': ^4.1.5
    '@vitest/ui': ^4.1.5
    jsdom: ^29.1.1
    vitest: ^4.1.5

  types:
    '@types/node': ^25.6.0
    '@types/react': ^19.2.0
    '@types/react-dom': ^19.2.0
    typescript: ^6.0.2

minimumReleaseAgeExclude:
  - electron@43.1.0
