/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: packages/ui-shared/src/theme/weArchiveTheme.ts
 * Command: astryx theme build packages/ui-shared/src/theme/weArchiveTheme.ts
 * Generated: 2026-07-10T07:21:24.856Z
 */

import type { DefinedTheme } from "@astryxdesign/core/theme";
export declare const wearchiveTheme: DefinedTheme;
