/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: packages/ui-shared/src/theme/weArchiveTheme.ts
 * Command: astryx theme build packages/ui-shared/src/theme/weArchiveTheme.ts
 * Generated: 2026-07-10T07:21:24.864Z
 */

// Generated by astryx theme build
export {};

declare module "@astryxdesign/core/Heading" {
  interface XDSHeadingLevelMap {
    "1": true;
    "2": true;
    "3": true;
    "4": true;
    "5": true;
    "6": true;
  }
}

declare module "@astryxdesign/core/SideNavItem" {
  interface XDSSideNavItemSelectedMap {
    selected: true;
  }
}
