// Generated by @tanstack/router-plugin
// prettier-ignore
export const fileRoutes = {
  "/$": {
    id: "/",
    path: "/",
    children: undefined,
  },
  "/backup-tasks": {
    id: "/backup-tasks",
    path: "/backup-tasks",
    children: undefined,
  },
  "/chat-records": {
    id: "/chat-records",
    path: "/chat-records",
    children: undefined,
  },
  "/import-export": {
    id: "/import-export",
    path: "/import-export",
    children: undefined,
  },
  "/restore": {
    id: "/restore",
    path: "/restore",
    children: undefined,
  },
  "/settings": {
    id: "/settings",
    path: "/settings",
    children: undefined,
  },
} as const;
